version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
    groups:
      nuxt:
        patterns:
          - "nuxt"
          - "@nuxt/*"
          - "@nuxtjs/*"
        update-types:
          - minor
          - patch
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - ci
